### ISSUE TITLE
JigsawGame.exe - 前置条件失败

### ISSUE THREAD

**Issue by lersh** [CYJB/Cyjb.Projects.JigsawGame#2]
谢谢博主，现在能编译通过并运行了
但是在选择完图片，点击确定后，会弹出报错框：
JigsawGame.exe - 前置条件失败
Description:必须使用代码协定二进制重写工具(CCRewrite)重写某个程序集(可能为"Cyjb")，因为它要调用 Contract.Requires，并且定义了CONTRACTS_FULL符号。从项目中删除CONTRACTS_FULL符号的任何显式定义并重新生成。……
等等好大一段

**Comment by CYJB** [comment]
目前使用了 [Code Contracts for .NET](https://visualstudiogallery.msdn.microsoft.com/1ec7db13-3363-46c9-851f-1ce455f66970) 作为 debug 模式的代码约束工具，因此需要安装这个工具，或者使用 release 模式编译。
